/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liteProto_LlpJavaNative */

#ifndef _Included_com_liteProto_LlpJavaNative
#define _Included_com_liteProto_LlpJavaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpNewEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpNewEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpFreeEnv
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpFreeEnv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRegMes
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRegMes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpDelMes
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpDelMes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageNew
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpMessageNew
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageClr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpMessageClr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpMessageFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_liteProto_LlpJavaNative_llpMessageFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesInt32
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesInt32
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesInt64
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesInt64
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesFloat32
 * Signature: (J[BF)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesFloat32
  (JNIEnv *, jclass, jlong, jbyteArray, jfloat);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesFloat64
 * Signature: (J[BD)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesFloat64
  (JNIEnv *, jclass, jlong, jbyteArray, jdouble);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesString
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpWmesString
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpWmesMessage
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpWmesMessage
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesInt32
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRmesInt32
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesInt64
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpRmesInt64
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesFloat32
 * Signature: (J[BI)F
 */
JNIEXPORT jfloat JNICALL Java_com_liteProto_LlpJavaNative_llpRmesFloat32
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesFloat64
 * Signature: (J[BI)D
 */
JNIEXPORT jdouble JNICALL Java_com_liteProto_LlpJavaNative_llpRmesFloat64
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesString
 * Signature: (J[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpRmesString
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesMessage
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_liteProto_LlpJavaNative_llpRmesMessage
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpRmesSize
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpRmesSize
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpOutMessage
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liteProto_LlpJavaNative_llpOutMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_liteProto_LlpJavaNative
 * Method:    llpInMessage
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_liteProto_LlpJavaNative_llpInMessage
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
